# Generated by Django 4.0.5 on 2022-06-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('on_delivery', 'On Delivery'), ('delivered', 'Delivered')], default='undelivered', max_length=50),
            preserve_default=False,
        ),
    ]
