# Generated by Django 4.0.5 on 2022-06-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
