# Generated by Django 4.0.5 on 2022-07-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('on_delivery', 'On Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
