# Generated by Django 4.0.5 on 2022-08-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash on Delivery', 'Cash on Delivery')], max_length=50),
        ),
    ]
