# Generated by Django 4.0.5 on 2022-06-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_created_date_product_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('grey', 'Grey'), ('silver', 'Silver'), ('golden', 'Golden')], max_length=100, null=True),
        ),
    ]
