# Generated by Django 4.0.5 on 2022-07-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_discriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default='name', upload_to='brandimage/'),
            preserve_default=False,
        ),
    ]
