# Generated by Django 4.0.5 on 2022-07-26 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_date_alter_attendance_status_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='first_in',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='last_out',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
